server.default_listen_address=0.0.0.0
server.default_advertised_address=neo4j
server.bolt.enabled=true
server.bolt.listen_address=0.0.0.0:7687
server.bolt.advertised_address=neo4j:7687
server.http.enabled=false
server.https.enabled=false
server.memory.heap.initial_size=256m
server.memory.heap.max_size=512m
server.memory.pagecache.size=256m
client.allow_telemetry=false
server.bolt.telemetry.enabled=false
