package launcher

import (
	"context"
	"crypto/ed25519"
	"errors"
	"runtime"

	firststartadapter "github.com/rickyseezy/AgentMemory/apps/launcher/internal/adapters/firststart"
	releaseverifyadapter "github.com/rickyseezy/AgentMemory/apps/launcher/internal/adapters/releaseverify"
	"github.com/rickyseezy/AgentMemory/apps/launcher/internal/application/firststartapp"
	appreleaseverify "github.com/rickyseezy/AgentMemory/apps/launcher/internal/application/releaseverify"
	"github.com/rickyseezy/AgentMemory/apps/launcher/internal/domain/releaseinventory"
)

const nativeReleaseProtocolVersion = uint32(1)

type nativeReleaseContentSource interface {
	releaseverifyadapter.ResourceContentSource
	appreleaseverify.DistributionEnvelopeSource
}

// nativeReleaseTrustMaterial is public verification material generated by the
// release pipeline and compiled into a signed launcher build. It deliberately
// contains no private key or credential.
type nativeReleaseTrustMaterial struct {
	ManifestKeys   map[string]ed25519.PublicKey
	HostPolicyKeys map[string]ed25519.PublicKey
	Offline        releaseverifyadapter.OfflineTrustPolicyInput
	Provenance     releaseverifyadapter.ProvenanceTrustPolicyInput
	Qualification  releaseverifyadapter.QualificationTrustPolicyInput
	Publishers     releaseverifyadapter.NativePublisherPolicyInput
}

type nativeReleaseStackDependencies struct {
	Source       nativeReleaseContentSource
	Clock        appreleaseverify.Clock
	AntiRollback appreleaseverify.AntiRollbackRepository
	Trust        nativeReleaseTrustMaterial
}

// nativeReleaseStack retains the complete release verifier and exposes only
// its verified first-start template source to pristine-start preparation.
type nativeReleaseStack struct {
	application *appreleaseverify.Application
	templates   *firststartadapter.VerifiedTemplateSource
}

// newNativeReleaseStack is the sole release-trust composition path used by
// the launcher. Every constructor below fails closed; there is no permissive
// verifier for development or offline installation.
func newNativeReleaseStack(dependencies nativeReleaseStackDependencies) (nativeReleaseStack, error) {
	if nilAny(dependencies.Source) || nilAny(dependencies.Clock) || nilAny(dependencies.AntiRollback) {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	signature, err := releaseverifyadapter.NewEd25519KeyIDVerifier(dependencies.Trust.ManifestKeys)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	offlinePolicy, err := releaseverifyadapter.NewOfflineTrustPolicy(dependencies.Trust.Offline)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	offline, err := releaseverifyadapter.NewCanonicalOfflineTrustVerifier(dependencies.Clock, offlinePolicy)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	provenancePolicy, err := releaseverifyadapter.NewProvenanceTrustPolicy(dependencies.Trust.Provenance)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	provenance, err := releaseverifyadapter.NewSLSAProvenanceVerifier(dependencies.Source, provenancePolicy)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	qualificationPolicy, err := releaseverifyadapter.NewQualificationTrustPolicy(dependencies.Trust.Qualification)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	qualification, err := releaseverifyadapter.NewSignedQualificationVerifier(
		dependencies.Source, dependencies.Clock, qualificationPolicy,
	)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	publishers, err := releaseverifyadapter.NewNativePublisherPolicyVerifier(dependencies.Trust.Publishers)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	digests, err := releaseverifyadapter.NewSHA256ResourceDigestVerifier(dependencies.Source)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	sboms, err := releaseverifyadapter.NewCanonicalSBOMVerifier(dependencies.Source)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	oci, err := releaseverifyadapter.NewCanonicalOCIIndexVerifier(dependencies.Source)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	application, err := appreleaseverify.NewApplication(appreleaseverify.Dependencies{
		Clock: dependencies.Clock, Platform: nativeReleasePlatform{}, Protocol: nativeReleaseProtocol{},
		Signature: signature, TrustEvidence: offline, ResourceDigest: digests,
		SBOM: sboms, Provenance: provenance, License: qualification, Vulnerability: qualification,
		NativePublisher: publishers, OCIIndex: oci, AntiRollback: dependencies.AntiRollback,
	})
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	bootstrap, err := appreleaseverify.NewBootstrapCatalog(dependencies.Source)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	verified, err := appreleaseverify.NewVerifiedDistributionCatalog(dependencies.Source, application, bootstrap)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	distribution, err := firststartadapter.NewDistributionTemplateCatalog(verified)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	templates, err := firststartadapter.NewVerifiedTemplateSource(distribution)
	if err != nil {
		return nativeReleaseStack{}, firststartapp.ErrIntegrity
	}
	return nativeReleaseStack{application: application, templates: templates}, nil
}

type nativeReleasePlatform struct{}

func (nativeReleasePlatform) CurrentPlatform(ctx context.Context) (releaseinventory.Platform, error) {
	if ctx == nil {
		return releaseinventory.Platform{}, errors.New("native release platform context is required")
	}
	if err := ctx.Err(); err != nil {
		return releaseinventory.Platform{}, err
	}
	platform, err := releaseinventory.NewPlatform(runtime.GOOS, runtime.GOARCH)
	if err != nil {
		return releaseinventory.Platform{}, errors.New("native release platform is unsupported")
	}
	return platform, nil
}

type nativeReleaseProtocol struct{}

func (nativeReleaseProtocol) CurrentProtocol(ctx context.Context) (uint32, error) {
	if ctx == nil {
		return 0, errors.New("native release protocol context is required")
	}
	if err := ctx.Err(); err != nil {
		return 0, err
	}
	return nativeReleaseProtocolVersion, nil
}

var (
	_ appreleaseverify.PlatformProvider = nativeReleasePlatform{}
	_ appreleaseverify.ProtocolProvider = nativeReleaseProtocol{}
)
